<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>se.gtradinit</groupId>
        <artifactId>GitJini</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>jini-example</artifactId>

    <dependencies>
        <dependency>
            <groupId>se.gtradinit</groupId>
            <artifactId>jini-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>se.gtradinit</groupId>
            <artifactId>jini-lookup</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>se.gtradinit</groupId>
            <artifactId>jini-discovery</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>se.gtradinit</groupId>
            <artifactId>jini-java-spaces</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
